# Cloudflare Workers 配置
name = "libretv"
main = "src/index.ts"
compatibility_date = "2023-12-01"

# 环境变量
[vars]
# PASSWORD = "111111"  # 在 Cloudflare Dashboard 中设置

# Assets 配置 (用于静态文件)
[assets]
directory = "./public"